name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check for changeset
        if: github.event_name == 'pull_request'
        run: yarn changeset status --since origin/main

      - name: Lint
        run: yarn lint:all

      - name: Type check
        run: yarn tsc

      - name: Build
        run: yarn build:all

      - name: Test
        run: yarn test:all
